#This is Docker File for Custom prometheus Docker Application  Instrumentation

FROM tiangolo/uwsgi-nginx-flask:python3.12

#COPY ./requirements.txt /app/requirements.txt

#RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

RUN pip install prometheus_client

ENV LISTEN_PORT=5001

EXPOSE 5001

COPY ./app /app

WORKDIR /app